---
- hosts: civicrm
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    date: "{{ lookup('pipe', 'date +\"%Y%m%d\"') }}"

  # does not work: wp civicrm upgrade --zipfile ../Downloads/civicrm-5.48.0-wordpress.zip
  # see https://lab.civicrm.org/dev/wordpress/-/issues/123

  # see https://docs.civicrm.org/sysadmin/en/latest/upgrade/wordpress/

  tasks:
  - name: put site into maintenance mode
    become: yes
    shell: |
      $HOME/bin/wp-cli.phar maintenance-mode activate || exit 0
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"

  - name: update wordpress core
    become: yes
    shell: |
      $HOME/bin/wp-cli.phar core update || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"

  - name: Check if the backup already exists
    become: yes
    stat:
      path: /home/pacs/{{pac}}/users/{{user}}/backup-civicrm-{{date}}.tar.gz
    register: stat_result

  - name: backup civicrm if there is no backup yet for today
    become: yes
    shell: |
      tar czf /home/pacs/{{pac}}/users/{{user}}/backup-civicrm-{{date}}.tar.gz wp-content/plugins/civicrm wp-content/uploads/civicrm/civicrm.settings.php || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"
    when: not stat_result.stat.exists

  - name: drop civi plugin
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm"
      state: absent

  - name: install civicrm plugin
    become: yes
    unarchive:
      creates: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm
      src: https://download.civicrm.org/civicrm-{{civicrm_version}}-wordpress.zip
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/

  - name: download civicrm translations directly
    become: yes
    unarchive:
      src: https://sourceforge.net/projects/civicrm/files/civicrm-stable/{{civicrm_version}}/civicrm-{{civicrm_version}}-l10n.tar.gz/download
      #src: https://download.pokorra.de/cache/202204/civicrm-{{civicrm_version}}-l10n.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm
      creates: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm/civicrm/l10n
    when: url_proxy is not defined

  - name: download civicrm translations from proxy
    become: yes
    unarchive:
      src: "{{url_proxy}}/civicrm-{{civicrm_version}}-l10n.tar.gz"
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm
      extra_opts: [--strip-components=1] # to avoid the civicrm directory
      creates: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/plugins/civicrm/civicrm/l10n
    when: url_proxy is defined

  - name: Capture all cached files
    become: yes
    find:
      paths: /home/pacs/{{pac}}/users/{{user}}/wordpress/wp-content/uploads/civicrm/templates_c
      excludes: 
        - ".htaccess"
    register: cached_files

  - name: Delete cached files
    become: yes
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ cached_files['files'] }}"

  # TODO: CiviCRM extensions should be installed in wp-content/uploads/civicrm/ext
  # TODO: Update the extensions???


  - name: activate civicrm
    become: yes
    shell: |
      $HOME/bin/wp-cli.phar plugin activate civicrm || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.civicrmactivated
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.civicrmactivated"

  # need to activate site to avoid issue with upgrades: Call to undefined function trailingslashit()
  - name: put site out of maintenance mode
    become: yes
    shell: |
      $HOME/bin/wp-cli.phar maintenance-mode deactivate || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"

  - name: update CiviCRM with cv
    become: yes
    shell: |
      ./cv.phar upgrade:db --no-interaction || exit -1
      # clear cache
      ./cv.phar flush || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/wordpress"

